"""Load an image file from the workspace into the model's context."""

from __future__ import annotations

import base64
from pathlib import Path
from typing import Any

from langchain_core.messages.content import create_image_block, create_text_block

_MAX_BYTES = 5 * 1024 * 1024  # 5 MB hard cap to keep token cost predictable


def _media_type(data: bytes) -> str | None:
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if data[:3] == b"\xff\xd8\xff":
        return "image/jpeg"
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return "image/gif"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "image/webp"
    return None


def view_image(path: str) -> list[dict[str, Any]] | str:
    """Read a PNG/JPEG/GIF/WEBP file and return it as a multimodal content block.

    Use this to look at:
    - Screenshots already saved by `screenshot` (e.g. `/tmp/dysprosium_screenshots/...`)
    - Playwright HTML report screenshots (e.g. `playwright-report/.../*.png`)
    - Design mocks or fixtures in the repo
    - Any image generated by a previous tool call

    Args:
        path: Filesystem path. Relative paths resolve against the current
            working directory; `~` is expanded.

    Returns:
        On success: a multimodal list with a one-line metadata text block
        and the image block. On failure (missing, too large, unrecognized
        format): a one-line error string.
    """
    p = Path(path).expanduser()
    if not p.is_absolute():
        p = p.resolve()
    if not p.is_file():
        return f"File not found: {path}"

    size = p.stat().st_size
    if size > _MAX_BYTES:
        return f"Image too large to inline: {path} is {size} bytes (max {_MAX_BYTES})"
    if size == 0:
        return f"File is empty: {path}"

    data = p.read_bytes()
    mime = _media_type(data)
    if mime is None:
        return f"Unrecognized image format for {path} (PNG / JPEG / GIF / WEBP only)"

    encoded = base64.b64encode(data).decode("ascii")
    return [
        create_text_block(f"Image: {p} ({mime}, {size} bytes)"),
        create_image_block(base64=encoded, mime_type=mime),
    ]
